[[constraint]]
  name = "github.com/andygrunwald/go-jira"
  version = "1.6.0"

[[constraint]]
  name = "github.com/asdine/storm"
  version = "2.2.0"

[[constraint]]
  name = "github.com/docopt/docopt-go"
  version = "0.6.2"

[[constraint]]
  branch = "master"
  name = "github.com/f2prateek/github-webhook-server"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/google/go-github"
  version = "24.0.1"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.4"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.5.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.2"

[prune]
  go-tests = true
  unused-packages = true
